{
 "title": "Cluster overview",
 "time": { "from": "now-5m", "to": "now-10s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": {
     "query": "label_values({job=\"openstack_exporter\", service=\"nova-scheduler\"}, hostname)"
    }
   },
   {
    "name": "Compute",
    "query": {
     "query": "label_values(container_tasks_state,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Status - $Controller",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "Controller",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"neutron_server\"} > time() - 60) by (name)",
     "legendFormat": "Neutron Server"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"nova_conductor\"} > time() - 60) by (name)",
     "legendFormat": "Nova Conductor"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"nova_api\"} > time() - 60) by (name)",
     "legendFormat": "Nova API"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"nova_scheduler\"} > time() - 60) by (name)",
     "legendFormat": "Nova Scheduler"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"keystone\"} > time() - 60) by (name)",
     "legendFormat": "Keystone"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"mariadb\"} > time() - 60) by (name)",
     "legendFormat": "MariaDB"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"haproxy\"} > time() - 60) by (name)",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"rabbitmq\"} > time() - 60) by (name)",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"placement_api\"} > time() - 60) by (name)",
     "legendFormat": "Placement API"
    },
    {
     "expr": "count(container_last_seen{instance=\"$Controller\", name=\"horizon\"} > time() - 60) by (name)",
     "legendFormat": "Horizon"
    }
   ]
  },
  {
   "title": "Compute Status - $Compute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "repeat": "Compute",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_up{instance=\"$Compute\", job=\"libvirt_exporter\"}",
     "legendFormat": "Libvirt"
    },
    {
     "expr": "openstack_nova_agent_state{hostname=\"$Compute\", service=\"nova-compute\"}",
     "legendFormat": "Nova compute"
    },
    {
     "expr": "openstack_neutron_agent_state{hostname=\"$Compute\",service=\"ovn-controller\"}",
     "legendFormat": "OVN Controller"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Resource Usage - $Compute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "repeat": "Compute",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$Compute\"}) / count(count(node_cpu_seconds_total{instance=\"$Compute\"}) by (cpu))",
     "legendFormat": "Host CPU Load"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$Compute\"} - node_memory_MemAvailable_bytes{instance=\"$Compute\"}) / node_memory_MemTotal_bytes{instance=\"$Compute\"} ",
     "legendFormat": "Host Memory Usage"
    },
    {
     "expr": "1 - (node_filesystem_avail_bytes{instance=\"$Compute\", mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"$Compute\", mountpoint=\"/\"})",
     "legendFormat": "Host Disk Usage"
    },
    {
     "expr": "openstack_placement_resource_usage{hostname=\"$Compute\", resourcetype=\"VCPU\"} / ((openstack_placement_resource_total{hostname=\"$Compute\", resourcetype=\"VCPU\"} - openstack_placement_resource_reserved{hostname=\"$Compute\", resourcetype=\"VCPU\"}) * openstack_placement_resource_allocation_ratio{hostname=\"$Compute\", resourcetype=\"VCPU\"})",
     "legendFormat": "Nova vCPU Usage"
    },
    {
     "expr": "openstack_placement_resource_usage{hostname=\"$Compute\", resourcetype=\"MEMORY_MB\"} / ((openstack_placement_resource_total{hostname=\"$Compute\", resourcetype=\"MEMORY_MB\"} - openstack_placement_resource_reserved{hostname=\"$Compute\", resourcetype=\"MEMORY_MB\"}) * openstack_placement_resource_allocation_ratio{hostname=\"$Compute\", resourcetype=\"MEMORY_MB\"})",
     "legendFormat": "Nova Memory Usage"
    },
    {
     "expr": "openstack_placement_resource_usage{hostname=\"$Compute\", resourcetype=\"DISK_GB\"} / ((openstack_placement_resource_total{hostname=\"$Compute\", resourcetype=\"DISK_GB\"} - openstack_placement_resource_reserved{hostname=\"$Compute\", resourcetype=\"DISK_GB\"}) * openstack_placement_resource_allocation_ratio{hostname=\"$Compute\", resourcetype=\"DISK_GB\"})",
     "legendFormat": "Nova Disk Usage"
    }
   ]
  }
 ]
}