{
 "title": "Instance",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Domain",
    "label": "Domain",
    "query": {
     "query": "label_values(openstack_identity_project_info,domain_id)"
    }
   },
   {
    "name": "Project",
    "label": "Project",
    "query": {
     "query": "label_values(openstack_identity_project_info{domain_id=~\"$Domain\"},name)"
    }
   },
   {
    "name": "UUID",
    "label": "UUID",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{project_name=~\"$Project\"},uuid)"
    }
   },
   {
    "name": "lib_domain",
    "label": "lib_domain",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{uuid=~\"$UUID\"},domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hypervisor",
   "type": "stat",
   "targets": [
    {
     "expr": "openstack_nova_server_status{uuid=~\"$UUID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_server_status{uuid=~\"$UUID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_server_status{uuid=~\"$UUID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flavor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_meta{uuid=~\"$UUID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_info_cpu_time_seconds_total{domain=\"$lib_domain\"}[5m]))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{domain=\"$lib_domain\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Block Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_bytes_total{domain=\"$lib_domain\"}[5m]))",
     "legendFormat": "READ - {{target_device}}"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_bytes_total{domain=\"$lib_domain\"}[5m]))",
     "legendFormat": "WRITE - {{target_device}}"
    }
   ]
  },
  {
   "title": "Block Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_requests_total{domain=~\"$lib_domain\"}[5m]))",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_requests_total{domain=~\"$lib_domain\"}[5m]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Bytes received / transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_bytes_total{domain=\"$lib_domain\"}[5m]))",
     "legendFormat": "RECEIVE - {{target_device}}"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_bytes_total{domain=\"$lib_domain\"}[5m]))",
     "legendFormat": "TRANSMIT - {{target_device}}"
    }
   ]
  },
  {
   "title": "Interface PPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_packets_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_packets_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "Interface Error/Drop",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_drops_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_drops_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_errors_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_errors_total{domain=\"$lib_domain\"} [5m]))",
     "legendFormat": "TX Error"
    }
   ]
  }
 ]
}