{
 "title": "OpenStack",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DomainID",
    "label": "Domain ID",
    "query": {
     "query": "label_values(openstack_identity_project_info,domain_id)"
    }
   },
   {
    "name": "ProjectName",
    "label": "Project Name",
    "query": {
     "query": "label_values(openstack_identity_project_info{domain_id=~\"$DomainID\", name!=\"service\"},name)"
    }
   },
   { "name": "Hostname", "label": "Hostname" }
  ]
 },
 "panels": [
  {
   "title": "vCPUs used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\"})/sum(openstack_placement_resource_total{resourcetype=\"VCPU\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\"})/sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local disk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"DISK_GB\"})/sum(openstack_placement_resource_total{resourcetype=\"DISK_GB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active VMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status{status=\"ACTIVE\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total vCPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total local disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"DISK_GB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inctive VMs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status{status!=\"ACTIVE\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "targets": [
    { "expr": "openstack_glance_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nova",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "targets": [
    { "expr": "openstack_nova_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keystone",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "targets": [
    { "expr": "openstack_identity_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{service=\"nova-compute\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "targets": [
    { "expr": "openstack_neutron_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "targets": [
    { "expr": "openstack_heat_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Placement",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "targets": [
    { "expr": "openstack_placement_up", "legendFormat": "__auto" }
   ]
  }
 ]
}