---
all:
  vars:
    project_name: ait

    kayobe_user: ubuntu

    kayobehost_mgmt_ip: 192.168.3.10
    kayobehost_mgmt_nic: eno8303

    kayobehost_idrac_nic: eno8403

    kayobehost_system_version: 22.04

    management_netmask: 24
    management_gw: 192.168.4.254
    management_dns: 192.168.4.254

    idrac_netmask: 24

    kayobevm_mgmt_ip: 192.168.4.9
    kayobevm_mgmt_nic: enp1s0
    kayobevm_idrac_ip: 192.168.3.9
    kayobevm_idrac_nic: enp2s0

    kayobevm_cpus: 4
    kayobevm_ram: "{{ 8 * 1024 }}"
    kayobevm_disk_size_gb: 200

  hosts:
    kayobevm:
      ansible_host: "{{ kayobevm_mgmt_ip }}"
      ansible_user: "{{ kayobe_user }}"
